"""The container image installs exactly the versions pyproject.toml pins (v1.1).

``requirements-image.lock`` is generated by scripts/lock_image_requirements.py;
these checks catch a lock that was not regenerated after a dependency change.
"""

from __future__ import annotations

import re
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def _locked(path: Path) -> dict[str, str]:
    pins: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        match = re.match(r"^([A-Za-z0-9_.\-]+)==([^\s;\\]+)", line)
        if match:
            pins[match.group(1).lower().replace("_", "-")] = match.group(2)
    return pins


def _pinned(requirements: list[str]) -> dict[str, str]:
    pins: dict[str, str] = {}
    for requirement in requirements:
        match = re.match(r"^([A-Za-z0-9_.\-]+)(?:\[[^\]]*\])?==(\S+)$", requirement.strip())
        assert match, f"pyproject dependency is not pinned exactly: {requirement}"
        pins[match.group(1).lower().replace("_", "-")] = match.group(2)
    return pins


def test_the_image_lock_matches_every_pinned_dependency():
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))["project"]
    expected = _pinned(project["dependencies"] + project["optional-dependencies"]["postgres"])
    locked = _locked(ROOT / "requirements-image.lock")
    stale = {name: (version, locked.get(name)) for name, version in expected.items() if locked.get(name) != version}
    assert not stale, f"regenerate with scripts/lock_image_requirements.py: {stale}"
    assert "psycopg-binary" in locked


def test_every_locked_requirement_carries_a_hash():
    for name in ("requirements-image.lock", "requirements-build.lock"):
        text = (ROOT / name).read_text(encoding="utf-8")
        entries = re.split(r"\n(?=[A-Za-z0-9])", text.strip())
        assert entries and all("--hash=sha256:" in entry for entry in entries), name
