"""Pilot rehearsal: two sovereigns through the production entry point.

    python scripts/pilot_rehearsal.py --postgres-url postgresql://user:pass@host:5432/postgres

Runs the pilot deployment profile (docs/operations/pilot-deployment-profile.md)
end to end. Each sovereign is a separate gunicorn Network Authority
(``genesis_mesh.na_service.wsgi:app``) configured only through environment
variables, as a container platform would configure it:

* **org-a**: single instance on SQLite, NA key from the environment.
* **bank-b**: ``NA_HA_MODE=on`` on its own PostgreSQL database, NA key from
  the environment, shared database rate limits.

Both run with ``NA_PROXY_HOPS=0`` (reached directly), required boundary
policy enforcement and the evidence store on. Each operator generates its own
root, NA and operator keys; only public material crosses between them.

The rehearsal then walks recognition to revocation: org-a reviews bank-b's
trust bundle and takes its key from bank-b's live endpoint, issues a scoped
treaty, accepts a bank-b member, sees the member revoked through bank-b's
signed feed, refuses a replayed and a forged feed, and checks that routine
(standard-tier) keys cannot change trust. Finally org-a's database is backed
up, restored into a new instance and verified. Exit status 0 when every check
passes.
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import signal
import socket
import subprocess
import sys
import tempfile
import time
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit, urlunsplit

import requests

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from genesis_mesh.crypto import generate_keypair, sign_data, sign_model  # noqa: E402
from genesis_mesh.models import (  # noqa: E402
    GenesisBlock, NetworkAuthority, PolicyManifestRef, SovereignRevocationFeed,
)

failures: list[str] = []


def check(name: str, ok: bool, detail: Any = "") -> None:
    print(f"  {'ok  ' if ok else 'FAIL'} {name}{'' if ok else f': {detail}'}", flush=True)
    if not ok:
        failures.append(f"{name}: {detail}")


def _free_port() -> int:
    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


class Sovereign:
    """One operator's sovereign: its own keys, genesis, database and gunicorn NA."""

    def __init__(self, name: str, work: Path, *, database_url: str | None = None) -> None:
        self.name = name
        self.work = work / name
        self.work.mkdir(parents=True)
        # Generated by this operator; the seeds go only into this NA's environment.
        self.root, self.na_key = generate_keypair(), generate_keypair()
        self.operator, self.operator_std = generate_keypair(), generate_keypair()
        now = datetime.now(timezone.utc)
        genesis = GenesisBlock(
            network_name=name, network_version="pilot", root_public_key=self.root.public_key_b64,
            network_authority=NetworkAuthority(public_key=self.na_key.public_key_b64, valid_from=now,
                                               valid_to=now + timedelta(days=365)),
            policy_manifest=PolicyManifestRef(hash="sha256:pilot", url=None),
        )
        genesis.signatures.append(sign_model(genesis, self.root.private_key, "root"))
        self.genesis_file = self.work / "genesis.signed.json"
        self.genesis_file.write_text(genesis.model_dump_json(), encoding="utf-8")
        self.db_path = str(self.work / "na.db")
        self.database_url = database_url
        self.proc: subprocess.Popen | None = None
        self.url = ""

    def env(self, db_path: str | None = None) -> dict[str, str]:
        env = {k: v for k, v in os.environ.items() if not k.startswith(("NA_", "DATABASE_URL", "DB_PATH"))}
        env.update({
            "GENESIS_FILE": str(self.genesis_file),
            "NA_KEY_PROVIDER": "env", "NA_KEY_ID": f"{self.name}-na",
            "NA_PRIVATE_KEY_SEED": self.na_key.private_key_b64,
            "OPERATOR_PUBLIC_KEYS_JSON": json.dumps({"ops": self.operator.public_key_b64,
                                                     "ops-std": self.operator_std.public_key_b64}),
            "OPERATOR_KEY_TIERS_JSON": json.dumps({"ops": "privileged", "ops-std": "standard"}),
            "BOUNDARY_POLICY_ENFORCEMENT": "required", "EVIDENCE_STORE": "on", "NA_PROXY_HOPS": "0",
        })
        if self.database_url:
            env.update({"DATABASE_URL": self.database_url, "NA_HA_MODE": "on", "RATE_LIMIT_STORE": "database"})
        else:
            env["DB_PATH"] = db_path or self.db_path
        return env

    def start(self, db_path: str | None = None) -> None:
        port = _free_port()
        self.url = f"http://127.0.0.1:{port}"
        log = (self.work / f"gunicorn-{port}.log").open("w")
        self.proc = subprocess.Popen(
            [sys.executable, "-m", "gunicorn", "--bind", f"127.0.0.1:{port}", "--workers", "2",
             "--timeout", "30", "genesis_mesh.na_service.wsgi:app"],
            env=self.env(db_path), cwd=str(self.work), stdout=log, stderr=subprocess.STDOUT,
        )
        deadline = time.monotonic() + 60
        while time.monotonic() < deadline:
            if self.proc.poll() is not None:
                raise SystemExit(f"{self.name} exited:\n{(self.work / log.name).read_text()[-3000:]}")
            try:
                if requests.get(self.url + "/readyz", timeout=2).status_code == 200:
                    return
            except requests.RequestException:
                pass
            time.sleep(0.3)
        raise SystemExit(f"{self.name} did not become ready")

    def stop(self) -> None:
        if self.proc and self.proc.poll() is None:
            self.proc.send_signal(signal.SIGTERM)
            try:
                self.proc.wait(timeout=20)
            except subprocess.TimeoutExpired:
                self.proc.kill()
        self.proc = None

    def admin(self, path: str, body: dict, *, standard: bool = False) -> requests.Response:
        key, key_id = (self.operator_std, "ops-std") if standard else (self.operator, "ops")
        ts, nonce = datetime.now(timezone.utc).isoformat(), str(uuid.uuid4())
        canonical = json.dumps({"body": body, "key_id": key_id, "timestamp": ts, "nonce": nonce},
                               sort_keys=True, separators=(",", ":"))
        headers = {"X-Admin-Key-Id": key_id, "X-Admin-Timestamp": ts, "X-Admin-Nonce": nonce,
                   "X-Admin-Signature": sign_data(canonical.encode("utf-8"), key.private_key)}
        return requests.post(self.url + path, json=body, headers=headers, timeout=10)


def _cli(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run([sys.executable, "-m", "genesis_mesh.cli.main", *args], capture_output=True, text=True,
                          cwd=str(ROOT))


def _code(resp: requests.Response) -> str | None:
    try:
        return resp.json().get("error", {}).get("code")
    except ValueError:
        return None


def rehearse(postgres_url: str) -> int:
    import psycopg

    db_name = f"gm_pilot_{uuid.uuid4().hex[:8]}"
    with psycopg.connect(postgres_url, autocommit=True) as conn:
        conn.execute(f"CREATE DATABASE {db_name} TEMPLATE template0 ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'C'")
    parts = urlsplit(postgres_url)
    bank_url = urlunsplit((parts.scheme, parts.netloc, f"/{db_name}", parts.query, parts.fragment))
    work = Path(tempfile.mkdtemp(prefix="gm-pilot-"))
    org = Sovereign("org-a", work)
    bank = Sovereign("bank-b", work, database_url=bank_url)
    try:
        org.start()
        bank.start()

        print("deployment:")
        for s, backend in ((org, "sqlite"), (bank, "postgres")):
            ready = requests.get(s.url + "/readyz", timeout=5).json()
            check(f"{s.name} ready on {backend} with its own key", ready.get("status") == "ready"
                  and ready["database"]["backend"] == backend
                  and ready["signing_key"]["provider"] == "env", ready)
        check("bank-b runs in HA mode with shared rate limits",
              requests.get(bank.url + "/readyz", timeout=5).json().get("ha_mode") == "on")
        check("no key material crosses sovereigns",
              org.na_key.private_key_b64 not in json.dumps(bank.env()) and
              bank.na_key.private_key_b64 not in json.dumps(org.env()))

        print("recognition:")
        bundle = work / "bank-b.bundle.json"
        exported = _cli("trust-bundle", "export", "--na", bank.url, "--output", str(bundle), "--format", "json")
        check("org-a exports bank-b's trust bundle", exported.returncode == 0, exported.stderr[-500:])
        validated = _cli("trust-bundle", "validate", "--bundle", str(bundle), "--na", bank.url, "--format", "json")
        check("the bundle is well-formed and matches bank-b's live endpoint", validated.returncode == 0,
              validated.stdout[-500:] + validated.stderr[-500:])
        live = requests.get(bank.url + "/sovereign.json", timeout=5).json()
        bank_key = live["network_authority"]["public_key"]
        check("bank-b's key taken from its live endpoint", bank_key == bank.na_key.public_key_b64, live)

        treaty_body = {"subject_sovereign_id": "bank-b", "subject_public_keys": [bank_key],
                       "scope": {"allowed_roles": ["role:client"]}, "validity_hours": 24 * 30}
        denied = org.admin("/admin/recognition-treaties", treaty_body, standard=True)
        check("a standard-tier key cannot issue a treaty", denied.status_code == 403
              and _code(denied) == "insufficient_operator_tier", denied.text[:300])
        resp = org.admin("/admin/recognition-treaties", treaty_body)
        check("org-a issues a scoped treaty for bank-b", resp.status_code == 201, resp.text[:300])
        treaty = resp.json()

        print("membership:")
        member_body = {"subject_id": "alice", "roles": ["role:client"], "claims": {"desk": "payments"}}
        denied = bank.admin("/admin/attestations", member_body, standard=True)
        check("a standard-tier key cannot issue an attestation", denied.status_code == 403, denied.text[:300])
        resp = bank.admin("/admin/attestations", member_body)
        check("bank-b attests its member", resp.status_code == 201, resp.text[:300])
        member = resp.json()
        resp = bank.admin("/admin/attestations", {"subject_id": "mallory", "roles": ["role:bridge"]})
        check("bank-b attests a member with a role the treaty does not grant", resp.status_code == 201,
              resp.text[:300])
        outsider = resp.json()

        def judged(att: dict) -> dict:
            return requests.post(org.url + "/attestations/verify-with-treaty",
                                 json={"attestation": att, "treaty": treaty}, timeout=10).json()

        r = judged(member)
        check("org-a accepts bank-b's member under the treaty", r.get("accepted") is True, r)
        r = judged(outsider)
        check("a role outside the treaty scope is rejected", r.get("reason") == "attestation_role_not_allowed", r)

        print("revocation:")
        resp = bank.admin(f"/admin/attestations/{member['attestation_id']}/revoke", {"reason": "left the bank"})
        check("bank-b revokes its member", resp.status_code == 200, resp.text[:300])
        feed = requests.get(bank.url + "/sovereign-revocation-feed", timeout=5).json()
        resp = org.admin("/admin/sovereign-revocation-feeds/import", {"feed": feed})
        check("org-a imports bank-b's signed feed", resp.status_code == 200 and resp.json().get("accepted"),
              resp.text[:300])
        r = judged(member)
        check("org-a now rejects the revoked member", r.get("reason") == "attestation_locally_revoked", r)
        replay = org.admin("/admin/sovereign-revocation-feeds/import", {"feed": feed})
        check("a replayed feed is refused", replay.status_code == 409 and _code(replay) == "stale_sequence",
              replay.text[:300])
        forger = generate_keypair()
        forged = SovereignRevocationFeed.model_validate({**feed, "sequence": feed["sequence"] + 5, "signatures": []})
        forged.signatures.append(sign_model(forged, forger.private_key, "bank-b-na"))
        bad = org.admin("/admin/sovereign-revocation-feeds/import", {"feed": forged.model_dump(mode="json")})
        check("a feed signed by another key is refused", bad.status_code == 400 and _code(bad) == "invalid_signature",
              bad.text[:300])

        print("recovery:")
        backup = work / "org-a.backup.db"
        made = _cli("managed", "backup", "--db-path", org.db_path, "--output", str(backup))
        check("online backup of org-a's database", made.returncode == 0 and backup.exists(), made.stderr[-500:])
        org.stop()
        restored = str(work / "org-a" / "restored.db")
        rest = _cli("managed", "restore", "--db-path", restored, "--backup", str(backup), "--yes")
        check("backup restored for a new instance", rest.returncode == 0, rest.stdout[-300:] + rest.stderr[-300:])
        org.start(db_path=restored)
        vdb = _cli("na", "verify-db", "--db-path", restored, "--genesis", str(org.genesis_file))
        check("na verify-db on the restored database", vdb.returncode == 0, vdb.stdout[-500:] + vdb.stderr[-500:])
        r = judged(member)
        check("the restored instance still rejects the revoked member",
              r.get("reason") == "attestation_locally_revoked", r)
        r = requests.get(org.url + f"/recognition-treaties/{treaty['treaty_id']}", timeout=5)
        check("the restored instance still holds the treaty", r.status_code == 200, r.text[:200])
        check("the restored instance is ready",
              requests.get(org.url + "/readyz", timeout=5).json().get("status") == "ready")
    finally:
        org.stop()
        bank.stop()
        with psycopg.connect(postgres_url, autocommit=True) as conn:
            conn.execute(f"DROP DATABASE IF EXISTS {db_name} WITH (FORCE)")
        if not failures:
            import shutil

            shutil.rmtree(work, ignore_errors=True)
        else:
            print(f"logs kept in {work}")
    print(f"{'PASSED' if not failures else 'FAILED'}: pilot rehearsal ({len(failures)} failures)")
    return 0 if not failures else 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--postgres-url", required=True)
    args = parser.parse_args()
    return rehearse(args.postgres_url)


if __name__ == "__main__":
    sys.exit(main())
